// Generated by view binder compiler. Do not edit!
package com.example.myapplicationformams.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myapplicationformams.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBabysCalendarBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final TextView DateQuestion;

  @NonNull
  public final Button NotesOpen;

  @NonNull
  public final EditText ProvidedDate;

  @NonNull
  public final TextView SelectedNotes;

  private ActivityBabysCalendarBinding(@NonNull ScrollView rootView, @NonNull TextView DateQuestion,
      @NonNull Button NotesOpen, @NonNull EditText ProvidedDate, @NonNull TextView SelectedNotes) {
    this.rootView = rootView;
    this.DateQuestion = DateQuestion;
    this.NotesOpen = NotesOpen;
    this.ProvidedDate = ProvidedDate;
    this.SelectedNotes = SelectedNotes;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBabysCalendarBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBabysCalendarBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_babys_calendar, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBabysCalendarBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.DateQuestion;
      TextView DateQuestion = ViewBindings.findChildViewById(rootView, id);
      if (DateQuestion == null) {
        break missingId;
      }

      id = R.id.NotesOpen;
      Button NotesOpen = ViewBindings.findChildViewById(rootView, id);
      if (NotesOpen == null) {
        break missingId;
      }

      id = R.id.ProvidedDate;
      EditText ProvidedDate = ViewBindings.findChildViewById(rootView, id);
      if (ProvidedDate == null) {
        break missingId;
      }

      id = R.id.SelectedNotes;
      TextView SelectedNotes = ViewBindings.findChildViewById(rootView, id);
      if (SelectedNotes == null) {
        break missingId;
      }

      return new ActivityBabysCalendarBinding((ScrollView) rootView, DateQuestion, NotesOpen,
          ProvidedDate, SelectedNotes);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
